version: "3"
services:
  db:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-db
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-web
    command: bundle exec rails s -p 3000
    ports:
      - 3000:3000
    links:
      - db
